title: "My TryHackMe Portfolio"
description: "Cybersecurity notes, labs, and writeups"
author: yourname
theme: jekyll-theme-minimal

# Optional extras
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

