title: "My TryHackMe Portfolio"
description: "Cybersecurity notes, labs, and writeups"
author: yourname
#theme: jekyll-theme-minimal
remote_theme: pages-themes/hacker@v0.2.0

# Optional extras
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

